owner: BeaverHouse
repo: service-status

sites:
  - name: AE Check API
    url: https://v1.api.haulrest.me/aecheck/docs
    slug: aecheck
  - name: BA Torment API
    url: https://v1.api.haulrest.me/ba-torment/
    slug: ba-torment

status-website:
  cname: status.haulrest.me
  logoUrl: https://blog.haulrest.me/img/favicon.svg
  name: Austin's API Status
  introTitle: Austin's API status monitoring site, powered by Upptime
  introMessage: Please report haulrest@gmail.com if you have any issues.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
